/*
 *  $RCSfile: CommandSucceeded.java,v $
 *
 *  Created on 15 May 2004 by Daniel Winterstein
 *  part of Proof General for Eclipse
 */
package ed.inf.proofgeneral.sessionmanager.events;

import ed.inf.proofgeneral.document.CmdElement;

/**
 * Event marking that a command has been successfully processed by the prover
 * (as opposed to CommandCausedErrorEvent)
 * Generated by SessionManager
 * @author Daniel Winterstein
 */
public class CommandSucceeded extends InternalEvent {
	public CommandSucceeded(String pgipMessage, Object cause) {
		super(pgipMessage, cause);
	}
	public CommandSucceeded(CmdElement content, Object cause) {
		super(content,cause);
	}
	
	public CmdElement getCommand() {
	    return parseTree instanceof CmdElement ? (CmdElement) parseTree : null;
	}
}
