/*
 *  $RCSfile: CommandProcessed.java,v $
 *
 *  Created on 15 May 2004 by Daniel Winterstein
 *  part of Proof General for Eclipse
 */
package ed.inf.proofgeneral.sessionmanager.events;

import ed.inf.proofgeneral.document.CmdElement;

/**
 * Event marking that a prover command is finished (and either a ComCausedError or ComSucceeded has been generated) 
 * Generated by SessionManager
 * @author Daniel Winterstein
 */
public class CommandProcessed extends InternalEvent {
	public CommandProcessed(CmdElement content, Object cause) {
		super(content,cause);
	}
	public CmdElement getCommand() {
	    return parseTree instanceof CmdElement ? (CmdElement) parseTree : null;
	}
}
